#!/bin/sh

print_help(){
  echo "========================="
  echo "This is package manager for ssh keys!\n"
  echo "Type the one of following commands:"
  echo "sshvm list - listing the available packages"
  echo "========================="
}

get_current(){
  curr=`readlink ~/.ssh`
  if [ -n "$curr" ]
  then
    curr=`readlink ~/.ssh | xargs -l basename`
  fi
  echo "$curr"
}

print_list(){
  echo "List of available packages:\n"
  curr=$(get_current)
  for dir in `ls -d ~/.sshvm/packages/* | xargs -l basename` 
  do
    if [ "$curr" -eq "$dir" ]; then
      echo "=>  $dir"
    else
      echo "    $dir"
    fi
  done
  echo "\n=> - current package"
}


case $1 in
"list") print_list;;
"current") v=$(get_current); echo "$v" ;;
"help"|*) print_help ;;
esac

